forgetmenote_web/forgetmenote_web/forgetmenote_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tracker/', include('tracker.urls')),
]

forgetmenote_web/forgetmenote_web/tracker/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^signup/$', views.sign_up, name='sign_up'),
    url(r'^task/create/$', views.create_task, name='task_create'),
    url(r'^task/$', views.list_tasks, name='list_tasks'),
    url(r'^task/view/$', views.view_task, name='task_view'),
    url(r'^task/edit/$', views.edit_task, name='task_edit'),
    url(r'^task/delete/$', views.delete_task, name='task_delete'),
    url(r'^task/complete/$', views.complete_task, name='task_complete'),
    url(r'^task/cancel/$', views.cancel_task, name='task_cancel'),
    url(r'^task/resume/$', views.resume_task, name='task_resume'),
    url(r'^task/copy/$', views.copy_task, name='task_copy'),
    url(r'^group/create/$', views.create_group, name='group_create'),
    url(r'^group/delete/$', views.delete_group, name='group_delete'),
    url(r'^group/view/$', views.view_group, name='group_view'),
    url(r'^group/edit/$', views.edit_group, name='group_edit'),
    url(r'^reminder/set/$', views.set_reminder, name='reminder_set'),
    url(r'^reminder/dismiss/$', views.dismiss_reminder, name='reminder_dismiss'),
    url(r'^permission/withdraw/$', views.withdraw_permission, name='permission_withdraw'),
    url(r'^permission/grant/$', views.grant_permission, name='permission_grant'),
    url(r'^repeat/set/$', views.set_repeat, name='repeat_set'),
    url(r'^repeat/unset/$', views.unset_repeat, name='repeat_unset'),
]

forgetmenote_web/forgetmenote_web/tracker/models.py
import dateutil.parser
from dateutil import rrule

from django.db import models
from django.contrib.auth.models import User

import forgetmenote


def nullable_int(value):
    return int(value) if value != 'None' else None


class EnumTypeField(models.Field):

    def __init__(self, enum_type, *args, **kwargs):
        self.enum = enum_type
        super().__init__(*args, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        return name, path, (self.enum, *args), kwargs

    def get_prep_value(self, value):
        return value.value

    def to_python(self, value):
        if isinstance(value, self.enum):
            return value

        if isinstance(value, str):
            value = int(value)

        if value is None:
            return value

        return self.enum(value)

    def from_db_value(self, value, expression, connection, context):
        return self.to_python(value)

    def get_internal_type(self):
        return 'IntegerField'


class RuleField(models.Field):

    def get_prep_value(self, value):
        if not value:
            return 'None'

        return '{} {} {} {} {}'.format(
            value._freq, value._interval, value._count,
            bool(value._byweekday), str(value._dtstart)
        )

    def to_python(self, value):
        if isinstance(value, rrule.rrule):
            return value

        if value is None:
            return value

        if value == 'None':
            return None

        args = value.split()

        byweekday = [rrule.MO, rrule.TU, rrule.WE,
                     rrule.TH, rrule.FR]
        if args[3] == 'False':
            byweekday = []

        rule = rrule.rrule(
            freq=nullable_int(args[0]), count=nullable_int(args[2]),
            byweekday=byweekday, interval=int(args[1]),
            dtstart=dateutil.parser.parse(args[4])
        )
        return rule

    def from_db_value(self, value, expression, connection, context):
        return self.to_python(value)

    def get_internal_type(self):
        return 'CharField'


class Group(models.Model):

    class ExplicitGroupManager(models.Manager):
        def create_object(self, creator_id, title):
            return self.create(creator_id=creator_id, title=title)

    creator = models.ForeignKey(User, on_delete=models.PROTECT,
                                related_name='created_groups')
    title = models.CharField(max_length=30)

    objects = ExplicitGroupManager()

    def __str__(self):
        return self.title


class Task(models.Model):

    class ExplicitTaskManager(models.Manager):

        def create_object(self, creator_id, parent_task_id, group_id,
                          title, description, deadline, priority, status,
                          creation_time, last_updated_time):
            return self.create(creator_id=creator_id, parent_task_id=parent_task_id,
                               group_id=group_id, title=title,
                               description=description, deadline=deadline,
                               priority=priority, status=status,
                               creation_time=creation_time,
                               last_updated_time=last_updated_time)

    creator = models.ForeignKey(User, on_delete=models.PROTECT,
                                related_name='created_tasks')
    parent_task = models.ForeignKey('Task', related_name='child_tasks',
                                    null=True, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.PROTECT,
                              related_name='tasks')
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=500, blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    creation_time = models.DateTimeField(editable=False)
    last_updated_time = models.DateTimeField(blank=True, null=True)
    priority = EnumTypeField(forgetmenote.Priority)
    status = EnumTypeField(forgetmenote.Status)
    repeat = models.BooleanField(blank=True, default=False)
    repeat_period = RuleField(max_length=100, null=True)
    related_tasks = models.ManyToManyField('Task', through='Relation',
                                           symmetrical=False)

    objects = ExplicitTaskManager()


class Reminder(models.Model):

    class ExplicitReminderManager(models.Manager):
        def create_object(self, task_id, time, status):
            return self.create(task_id=task_id, time=time, status=status)

    task = models.ForeignKey(Task, on_delete=models.CASCADE,
                             related_name='reminders')
    time = models.DateTimeField()
    status = EnumTypeField(forgetmenote.ReminderStatus)

    objects = ExplicitReminderManager()


class Permission(models.Model):
    class ExplicitPermissionManager(models.Manager):
        def create_object(self, task_id, user_id, access_type):
            return self.create(task_id=task_id, user_id=user_id,
                               access_type=access_type)

    task = models.ForeignKey(Task, on_delete=models.CASCADE,
                             related_name='permissions')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='available_permissions')
    access_type = EnumTypeField(forgetmenote.AccessType)

    objects = ExplicitPermissionManager()


class Relation(models.Model):
    class ExplicitRelationManager(models.Manager):
        def create_object(self, creator_id, from_task_id, to_task_id, relation_type):
            return self.create(creator_id=creator_id, from_task_id=from_task_id,
                               to_task_id=to_task_id, relation_type=relation_type)

    from_task = models.ForeignKey(Task, on_delete=models.CASCADE,
                                  related_name='related_to')
    to_task = models.ForeignKey(Task, on_delete=models.CASCADE,
                                related_name='related_from')
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    relation_type = EnumTypeField(forgetmenote.RelationType)

    objects = ExplicitRelationManager()

forgetmenote_web/forgetmenote_web/tracker/forms.py
from django import forms
from django.utils.translation import gettext_lazy

from forgetmenote import Priority, AccessType

from . import models


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class TaskForm(forms.ModelForm):

    class Meta:
        model = models.Task
        fields = ['group', 'title', 'description', 'deadline', 'priority']
        widgets = {
            'deadline': forms.DateTimeInput(format='%Y-%m-%d %H:%M'),
            'description': forms.Textarea(),
            'priority': forms.Select(choices=[(item.value, item.name) for item in Priority])
        }
        help_texts = {
            'deadline': gettext_lazy('format - Y-m-d H:M'),
        }


class PermissionForm(forms.ModelForm):

    class Meta:
        model = models.Permission
        fields = ['user', 'access_type']
        widgets = {
            'access_type': forms.Select(choices=[(item.value, item.name) for item in AccessType])
        }

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html lang="en">
<title>{% block title %}{% endblock %} | forget-me-NOTe</title>
{% block includes %}
<link rel="stylesheet" href="{% static 'tracker/css/style.css' %}">
{% bootstrap_css %}
<script type="text/javascript" src="{% static 'tracker/js/jquery-3.3.1.js' %}"></script>
<script>
    $(document).ready(function () {
        {% block js %}
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        {% endblock %}
    })
</script>
{% endblock %}
</head>
<body>
{% block header %}
<div class="header" id="header">
    <a href="{% url 'home' %}" class="logo">forget-me-NOTe</a>
    <div class="header-right">
        {% block menu %}
        {% if user.is_authenticated %}
        {% if action != 'Create'%}<a href="{% url 'task_create' %}">Create task</a> {% endif %}
        <a href="{% url 'logout' %}">Logout</a>
        {% endif %}
        {% endblock %}
    </div>
</div>
{% endblock %}
<div id="container" class="container" style="padding-top: 10px; margin-bottom: 20px">
    {% block content %}{% endblock %}
</div>
{% block footer %}
<div class="footer">
    <p>Angelina Belyasova</p>
</div>
{% endblock %}
</body>
</html>

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/group_view.html
{%extends "tracker/base.html"%}

{% block title %}{{group.title}}{% endblock %}

{% block js %}
{{block.super}}
var group_id = {{group.id}}

$("#edit").click(function() {
    $("#title").hide()
    $("#edit").hide()
    $("#titleEdit").children("form").show()
    $("#newTitle").val($("#title").text())
})

$("#save").click(function() {
     $.ajax({
        type: 'POST',
        url: '/tracker/group/edit/',
        data: {
            'title': $("#newTitle").val(),
            'group_id': group_id
        },
        success: function (result, status, xhr) {
            $("#titleEdit").children("form").hide()
            $("#title").text(result['title'])
            $("#title").show()
            $("#edit").show()
        },
        error: function (xhr, status, error) {
            return
        }
    })
})

$("#cancel").click(function() {
    $("#titleEdit").children("form").hide()
    $("#title").show()
    $("#edit").show()
})
{% endblock %}

{% block menu %}
<a href="{% url 'list_tasks' %}">Tasks</a>
{{block.super}}
{% endblock %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        <div class="well">
            <label for="title">Title: </label>
            <span id="titleEdit">
                <span id="title">{{group.title}}</span>
                <form style="display: none" method="post" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <input id="newTitle" class="form-control">
                    </div>
                    <div class="form-group">
                        <button type="button" id="save" class="btn btn-primary">Save</button>
                        <button type="button" id="cancel" class="btn btn-warning">Cancel</button>
                    </div>
                </form>
                <button id="edit" class="btn btn-primary pull-right">Edit</button>
            </span>
        </div>
        <div class="well">
            <label for="creator">Creator: </label>
            <span id="creator">{{group.creator}}</span>
        </div>
        <div class="well">
            <label for="tasks"><h4>Tasks:</h4></label>
            <ul id="tasks" class="list_group">
                {% for task in tasks %}
                    <li class="row">
                        <a href="{% url 'task_view' %}?task_id={{task.id}}" class="list-group-item">{{task.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block includes %}
<link rel="stylesheet" type="text/css" href="{% static 'tracker/css/todolist_styles.css' %}">
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}

var myNodelist = document.getElementsByTagName("LI");
var i;
for (i = 0; i < myNodelist.length; i++) {
    var span = document.createElement("SPAN");
    var txt = document.createTextNode("\u00D7");
    span.className = "close";
    span.appendChild(txt);
    myNodelist[i].appendChild(span);
}

$(".close").click(function() {
    element = $(this)
    $.ajax({
        type: 'POST',
        url: '/tracker/group/delete/',
        data: {
            'group_id': element.parent().attr('id')
        },
        success: function (result, status, xhr) {
            element.parent().hide()
        },
        error: function (xhr, status, error) {
            alert('Apparently, group is not empty')
        }
    })
})

// Create a new list item when clicking on the "Add" button
function newElement() {
    var li = document.createElement("li");
    var inputValue = document.getElementById("titleInput").value;
    var redirect_url = '{% url 'group_view' %}' + '?group_id='
    $.ajax({
        type: 'POST',
        url: '/tracker/group/create/',
        data: {
            'title': inputValue
        },
        success: function (result, status, xhr) {
            newId = result['group_id']
            li.id = newId
            $(li).children('a').prop('href', redirect_url + newId)
        },
        error: function (xhr, status, error) {
            return
        }
    })
    var t = document.createTextNode(inputValue + "  ");
    var ref = document.createElement("A");
    ref.appendChild(t);
    li.appendChild(ref);
    if (inputValue === '') {
        alert("You must write something!");
    } else {
        document.getElementById("groups").appendChild(li);
    }
    document.getElementById("titleInput").value = "";

    var badge = document.createElement("SPAN");
    var txt = document.createTextNode("0");
    badge.className = "badge";
    badge.appendChild(txt);
    li.appendChild(badge);

    var span = document.createElement("SPAN");
    var txt = document.createTextNode("\u00D7");
    span.className = "close";
    span.appendChild(txt);
    li.appendChild(span);

    $(span).click(function() {
        element = $(this)
        $.ajax({
            type: 'POST',
            url: '/tracker/group/delete/',
            data: {
                'group_id': element.parent().attr('id')
            },
            success: function (result, status, xhr) {
                element.parent().hide()
            },
            error: function (xhr, status, error) {
                alert('Apparently, group is not empty')
            }
        })
    })
}

document.getElementById("addButton").addEventListener("click", newElement, false);

{% endblock %}

{% block menu %}
<a href="{% url 'list_tasks' %}">Tasks</a>
{{ block.super }}
{% endblock %}

{% block content %}
{% csrf_token %}
<!--<h2 style="text-align: center"><strong>Welcome, {{user}}!</strong></h2>-->
<div id="div" class="header">
    <h2 style="color: black;">Your groups</h2>
    <input type="text" id="titleInput" style="color: black" placeholder="Title...">
    <span id="addButton" class="addBtn">Add group</span>
</div>

<ul id="groups">
    {% for group in groups %}
    <li id="{{group.id}}">
        <span><a href="{% url 'group_view' %}?group_id={{group.id}}">{{group.title}}</a></span>
        <span class="badge">{{group.tasks_number}}</span>
    </li>
    {% endfor %}
</ul>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/login.html
{% extends "tracker/base.html" %}

{% block title %}Log in{% endblock %}

{% block menu %}
    {{ block.super }}
    <a href="{% url 'sign_up' %}">Sign up</a>
{% endblock %}

{% block content %}
{% load bootstrap3 %}
<form method="post" class="form-horizontal" novalidate>
    {% csrf_token %}
    <h1>Login</h1>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
        {{error}}
    </div>
    {% endif %}
    <hr>
    {% bootstrap_form form %}
    <hr>
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        Login
    </button>
    {% endbuttons %}
</form>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/permission_grant.html
{%extends "tracker/base.html"%}
{% block title %}Permission{% endblock %}

{% block menu %}
    <a href="{% url 'list_tasks' %}">Tasks</a>
    {{ block.super }}
{% endblock %}

{% block content %}
{% load bootstrap3 %}
{% if error %}
<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  {{error}}
</div>
{% endif %}
<form method="post" class="form-horizontal well" novalidate>
  <h1>New permission</h1>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Grant
    </button>
    <a href="{% url 'task_view' %}?task_id={{task_id}}"><button type="button" class="btn btn-default">Back to task view</button></a>
  {% endbuttons %}
</form>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/sign_up.html
{% extends "tracker/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
{% load bootstrap3 %}
<form method="post" class="form-horizontal" novalidate>
    {% csrf_token %}
    <h1>Sign up</h1>
    {% if error %}
    <div class="alert alert-danger">
        {{ error }}
    </div>
    {% endif %}
    <hr>
    {% bootstrap_form form %}
    <hr>
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        Confirm
    </button>
    <a href="{% url 'login' %}">
        <button type="button" class="btn btn-link">Return</button>
    </a>
    {% endbuttons %}
</form>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/task_editable.html
{%extends "tracker/base.html"%}
{% block title %}{{action}} task{% endblock %}

{% block menu %}
    <a href="{% url 'list_tasks' %}">Tasks</a>
    {{ block.super }}
{% endblock %}


{% block js %}
{{block.super}}
{% if action == 'Copy' %}
$(".form-control").not("#id_deadline").parent().hide()
{% endif %}
{% endblock %}

{% block content %}
{% load bootstrap3 %}
<form method="post" class="form-horizontal well" novalidate>
  <h1>{{action}} task</h1>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {{action}}
    </button>
    {% if action == 'Create' %}<a href="{% url 'list_tasks' %}"> {% else %}<a href="{% url 'task_view' %}?task_id={{task_id}}"> {% endif %}
        <button type="button" class="btn btn-link">Go{% if action == 'Create' %} to the list {% else %} back {% endif %}</button>
    </a>
  {% endbuttons %}
</form>
{% endblock %}

forgetmenote_web/forgetmenote_web/tracker/templates/tracker/task_list.html
{%extends "tracker/base.html"%}
{% block title %}Tasks{% endblock %}
{% block menu %}
{{ block.super }}
{% endblock %}
{% block content %}
<div class="row">
    <h1 class="page-header">Your tasks</h1>
    <div class="well">
        {% if tasks %}
        {% for s, o in status %}
        <div id="{{s}}_tasks">
            <h4><strong>{{ s|capfirst }}:</strong></h4>
            <ul class="list_group">
                {% for task in tasks %}
                {% if task.status is o %}
                <li class="row" id="{{task.id}}">
                        <a href="{% url 'task_view' %}?task_id={{task.id}}" class="list-group-item">
                            {{task.title}}
                        </a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% if not forloop.last %}
        <hr>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}